name: Software suggestions
description: Did you discover a new continent?
labels: package-request
body:
  - type: input
    attributes:
      label: Cask name
    validations:
      required: true
  - type: input
    attributes:
      label: Official website
    validations:
      required: true
  - type: input
    attributes:
      label: Lastest release date
    validations:
      required: true
  - type: input
    attributes:
      label: Description
    validations:
      required: true
  - type: input
    attributes:
      label: Download URL
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Charging model
      multiple: true
      options:
        - Free
        - Buyout
        - Subscription
    validations:
      required: true
