name: bump-intel

on:
  # pull_request:
  #   branches: [main]
  # push:
  #   branches: [fix-*]
  schedule:
    # Every 12 hours
    # - cron: "20 */12 * * *"
    # Every day at 6am
    - cron: "0 8 * * *"
  # allow run manually
  workflow_dispatch:

permissions: write-all

jobs:
  bump-formulae:
    name: Bump formulae
    if: github.repository == 'brewforge/homebrew-chinese'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13]

    steps:
      - uses: actions/checkout@v3

      - name: Homebrew env
        uses: ./.github/actions/homebrew-env

      - name: Brew Tap
        uses: ./.github/actions/brew-tap

      - name: Git Cred
        uses: ./.github/actions/git-cred
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      - name: Bump
        env:
          HOMEBREW_DEVELOPER: "1"
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        shell: bash -ieo pipefail {0}
        run: |
          rsync -lrv --exclude=.git "$(pwd)" "$(brew --repository brewforge/chinese)"
          cd "$(brew --repository brewforge/chinese)"
          ./.github/actions/bump-formulae/script.sh

  bump-formulae-linux:
    name: Bump formulae (Linuxbrew)
    if: github.repository == 'brewforge/homebrew-chinese'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3

      - name: Linuxbrew env
        uses: ./.github/actions/linuxbrew-env

      - name: Brew Tap
        uses: ./.github/actions/brew-tap

      - name: Git Cred
        uses: ./.github/actions/git-cred
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      - name: Bump
        env:
          HOMEBREW_DEVELOPER: "1"
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        shell: bash -ieo pipefail {0}
        run: |
          rsync -lrv --exclude=.git "$(pwd)" "$(brew --repository brewforge/chinese)"
          cd "$(brew --repository brewforge/chinese)"
          ./.github/actions/bump-formulae/script.sh
